### ISSUE TITLE
Post-conference TODO list

### ISSUE THREAD

**Issue by drewbrew** [djangocon/2021.djangocon.us#172]
- [x] CoC transparency report
- [ ] Put up the "that's all, folks" front page
- [ ] Send survey to ticket holders asking for feedback and interest in 2022 (include sponsor blurb from STG)
